--[[
TROJAN TECHNOLOGIES
Trojan.lua
Vanilla
1.0.0
cizzles
]]--

--> PRESET; DO NOT CONFIGURE ANYTHING IN THIS SCRIPT

local TeleportService = game:GetService("TeleportService")
local ReplicatedFirst = game:GetService("ReplicatedFirst")
local Players = game:GetService("Players")

local Player = Players.LocalPlayer

local PlayerGui = Player:WaitForChild("PlayerGui")

local Word_Bank = {

	"LOADING",
	"Does anyone even read these?",
	"Mom, get the camera!",
	"cizzles was here",
	"Bricks: 1337 Connectors: 0",
	"Roblox is updating",
	"Configuring Roblox",
	"Uninstalling Roblox",
	"Configuring Roblox Studio",
	"Not Again",
	"TEH EPIK DUCK IS COMING!!!",
	"THEY'RE REMOVING TIX?",
	"Removing Tix",
	"Adding spicy memes",
	"Press Alt + F4",
	"shut up nerd",
	"Cher, get in here!",
	"Dude, you've been in here for like 2 hours, get out",
	"Wash your hands next time",
	"Trojan Technologies: The Original",
	"Vanilla, are you serious?",
	"Vanilla is my favorite ;)",
	"Compiling data",
	"Is this thing on?",
	"Running Trojan.exe",
	"Well that didn't work",
	"/e hug",
	"/e free",
	"Flush next time",
	"/e dance",
	"/e dance2",
	"/e dance3",
	"Ping",
	"Pong",
	"Connecting",
	"Loading",
	"Downloading cat photos",
	"Sending a funny minion meme",
	"Coming soon to a theater near you",
	"Don't tell Mom",
	"Dividing by zero",
	"Zero-based indexing",
	"When's the next update? When's the next update? When's the next update?",
	"IT'S FREE!",
	"HAS SOUND",
	"Now in 1D",
	"As seen on TV!",
	"Not a good pick up line",
	"Installing dating apps on your phone",
	"Using advanced neural networks and algorithms to download cat photos off the Internet",
	"Not a dating app",
	"Who said that Lua was easy to learn?",
	"Adding funny comments to scripts",
	"Yeah, I'm just deleting this useless code-",
	"-- Can you see this?",
	"Hold on I'm copy and pasting my code from the Internet",
	":)",
	"Hey Siri, what's zero divided by zero?",
	"print() > Debugger",
	"Roblox vs. Minecraft",
	"Cats vs. Dogs",
	"Google < Roblox DevForum & Scripting Helpers > Stack Overflow",
	"Spending all my DevEx money on Teslas and microwaved pizzas",
	"Buying Teslas",
	"Me: I'm so sorry my dog ate my homework.\n Computer Science Professor: Your dog ate your homework? \n Me: \n Computer Science Professor: \n Me: It took him a couple bytes",
	"Scrolling through memes",
	"Arrays start at 1",
	"Starting an array at 0, are you crazy, who came up with this nonsense?",
	"Baking cookies",
	"Lua amirite??",
	"Programmer Humor",
	"Playing Monkey Game",
	"Updating Wiki",
	"Classy",
	"11 herbs and spices",
	"OOF",
	"Talking to your Girlfriend",
	"Going out for some milk",
	"Closed on Sundays",
	"Sending memes",
	"Buying Dogecoin",
	"Protects against 99.99% of noobs",
	"Get Rekt Nub",
	"Pwning noobs",
	"Playing Bug Smasher",
	"Ask your Doctor",
	"Comes with free dental insurance",
	"Avada Kedavra!",
	"Too much spice! TOO MUCH SPICE!!!",
	"You didn't see this",
	"Definitely Water Proof",
	"1x1x1x1",
	"The password is password",
	"There's a spider on your shoulder",
	"There's no Uber in Kansas?",
	"Don't look behind you",
	"Made you look! HAHA",
	"HAHA",
	"LOL",
	"XD",
	"Duck",
	"Goose",
	"MOM!?",
	"Incoming message",
	"Impending doom",
	"Doing barrel rolls",
	"Typing at 200 WPM",
	"200 IQ",
	"TROLOLO",
	"Now in Lua!",
	"Lua Edition",
	"CALL MOM!",
	"In case it isn't obvious these messages aren't real",
	"Cat, get off my keyboard",
	"What's that on your computer?",
	"It's... It's... Trojan Technologies. I swear! It just popped up on my screen for a second and I accidentally clicked it",
	"Plants vs. Zombies",
	"Installing antivirus software",
	"Slightly misleading content",
	"Probably safe",
	"Not for children under 5 years",
	"Better than the competition",
	"Going plaid",
	"Paying for your funeral",
	"1000% Funnier",
	"Heat waves",
	"Top 10 Loading Screen Fails",
	"Emitting blue light",
	"Smelling up the place",
	"Do you smell that?",
	"Adding Dad Jokes",
	"Turning on the jet engines",
	"Regenerating brakes",
	"Respawning the Ender Dragon",
	"Filtering chat messages",
	"Lualicious",
	"Spreading malware",
	"Lua for Losers",
	"Gotta Catch Them All",
	"SQL Injecting",
	"It's tax avoidance, not tax evasion, c'mon man",
	"Definitely paying taxes",
	"Sorry IRS",
	"Updating rank",
	"Watching funny cat videos",
	"BRB my PC just set on fire",
	"Sending streaks",
	"Is that real?",
	"4REALZLOL",
	"Definitely not hiding",
	"What are you hiding?",
	"Taking my time",
	"Taking longer than usual",
	"Solving basic math problems for script kiddies",
	"Zero-based indexing > one-based indexing",
	'print("Hello World")',
	"Hitting ny head on everything",
	"Falling down the stairs",
	"Mispelling everything",
	"Inserting free models",
	"Injecting viruses",
	"Adding viruses",
	"Removing viruses",
	"Using flamethrower on bugs",
	"Now Selling: Trojan Technologies Brick",
	"AFK",
	"No one reads the documentation",
	"Crash Roblox",
	"Crashing Roblox Studio",
	"Going back to the future",
	"Is this time machine working?",
	"Putting phone in the microwave",
	"Gone fishing",
	"Busy tailgating",
	"We're off to the races!",
	"Your Mom loves Trojan Technologies",
	"Not a good birthday gift",
	"Not a good Christmas gift",
	"Using my advanced artificial intelligence to invent new languages",
	"Restarting server",
	"Working on the weekend like usual",
	"Sue me bro",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan",
	"Trendsetter",
	"Set Trends",
	"Inserting pop culture reference*",
	"Checking your search history",
	"Doing the photosynthesis of the arithmetic succession plate sequence using the bor-trojan logic methods",
	"I hate it here",
	"Earning minimum wage",
	"Just got a Dogecoin tattoo, what do you think?",
	"Tattoos are permanent?",
	"Wasting my Robux",
	"Stealing user data",
	"ERROR: DATA CORRUPTED DURING TRANSMISSION",
	"Beam me up, cizzles",
	"You don't know what a bubbler is?",
	"Flossing",
	"Default dancing",
	"MOM YOU CAN'T PAUSE THE GAME",
	"It's not a phase Mom, it's a lifestyle",
	"Entering Mom's basement",
	"Chez Burger",
	"Nom nom nom",
	"Can I get 5 double cheeseburgers with extra fries, extra cheese, extra pickle, extra onion, extra patty, extra bun, extra ketchup, and with some extra packets of that sauce stuff on the side. Oh, and actually I need to start eating more healthy so make that soda a diet small with extra ice.",
	"You don't serve food here?",
	"Where's the food!?",
	"It's peanut butter jelly time!!!",
	"Sorry sir, we're going to have to move you to the kiddie table",
	"You smell like soap",
	"You smell like soap, but in a good way",
	"HAHA, JK!",
	"Writing more loading prompts",
	"Getting abducted by aliens",
	"Duckroll",
	"Crank that",
	"O RLY?",
	"Wombo Combo",
	"Happy Feet",
	"LOL cats",
	"I can has cheezburger?",
	"T R I P P Y   F R O G",
	"Playing train simulator",
	"Not an FPS game",
	"Spamming POGGERS",
	"Spamming HYPERS",
	"Inserting microchip",
	"Downloading data",
	"Transferring files",
	"Teleporting player",
	"Buying bath water",
	"Frying servers",
	"Breaching the perimeter",
	"Spamming OOF",
	"Spamming L",
	"me > you",
	"Copying the YouTube tutorial",
	"Stalking your social media",
	"Scrolling through my Twitter feed",
	"Scrolling through my For You page",
	"Retweeting Dogecoin memes",
	"Anticipating Elon's next tweet",
	"Stealing your data and uploading it to the Trojan Technologies database",
	"Upgrading Mom's Basement",
	"Restocking Snacks",
	"Restocking Mini Fridge",
	"Refreshing website for the next drop",
	"https://youtu.be/dQw4w9WgXcQ",
	"You just got rickrolled lol",
	"lol",
	"Anticipating opponents next move",
	"Becoming a Grandmaster at Chess",
	"CashApp Please Sponsor Me",
	"Telepathically communicating",
	"Ignoring your texts",
	"Ignoring your messages",
	"Ignoring your phone calls",
	"Leaving you on read",
	"Messaging your Mom",
	"Is that my Mom in the background? Uh... Yeah... I'm um...teaching her Lua!",
	"Clean your room",
	"Getting tendies",
	"Earning good boy points",
	"PLEASE, I'LL DO ANYTHING! Anything? Anything",
	"Sus",
	"SUS",
	"Ejecting the Imposter",
	"Red is sus",
	"Earning Reddit Karma",
	"Reddit Gold",
	"Achievement Unlocked: Loading",
	"Trojan Technologies: Trojan Technologies: Trojan Technologies",
	"Refreshing my YouTube home page",
	"The algorithm knows everything",
	"Bumping my T-Swift playlist on Spotify",
	" ",
	
}

if script.Parent == ReplicatedFirst then
	local Main = script:WaitForChild("Welcome To Trojan"):Clone()
	local Loading = Main:WaitForChild("Background"):WaitForChild("Heading")
	
	Main.Parent = PlayerGui
	
	TeleportService:SetTeleportGui(Main)
	
	while true do
		local Word = math.random(1, #Word_Bank)
		local Text = tostring(Word_Bank[Word])
		wait(0.5)
		Loading.Text = string.format("%s", Text)
		wait(0.5)
		Loading.Text = string.format("%s.", Text)
		wait(0.5)
		Loading.Text = string.format("%s..", Text)
		wait(0.5)
		Loading.Text = string.format("%s...", Text)
		wait(0.5)
	end
end

--> Copyright 2020-2021 Trojan Technologies. © All rights reserved.
